/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package calculadora;

/**
 *
 * @author guilh
 */
public class FormCalculadora extends javax.swing.JFrame {

    /**
     * Creates new form FormCalculadora
     */
    public FormCalculadora() {
        initComponents();
    }
    
    Double value1,value2,n,factorial;
    String signal;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btn_value7 = new javax.swing.JButton();
        btn_value8 = new javax.swing.JButton();
        btn_Sum = new javax.swing.JButton();
        btn_value9 = new javax.swing.JButton();
        btn_ClearResult = new javax.swing.JButton();
        btn_value4 = new javax.swing.JButton();
        btn_value5 = new javax.swing.JButton();
        btn_value6 = new javax.swing.JButton();
        btn_ClearVariebleResult = new javax.swing.JButton();
        btn_Subtraction = new javax.swing.JButton();
        btn_value1 = new javax.swing.JButton();
        btn_value2 = new javax.swing.JButton();
        btn_value3 = new javax.swing.JButton();
        btn_Equal = new javax.swing.JButton();
        btn_Multiplication = new javax.swing.JButton();
        btn_value0 = new javax.swing.JButton();
        btn_Score = new javax.swing.JButton();
        btn_Division = new javax.swing.JButton();
        txt_Result = new javax.swing.JTextField();
        btn_Square = new javax.swing.JButton();
        btn_Cube = new javax.swing.JButton();
        btn_SquareRoot = new javax.swing.JButton();
        btn_Factorial = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        lbl_Calculator = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(51, 51, 51));

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setForeground(new java.awt.Color(51, 51, 51));

        btn_value7.setBackground(new java.awt.Color(0, 0, 0));
        btn_value7.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 18)); // NOI18N
        btn_value7.setForeground(new java.awt.Color(255, 255, 255));
        btn_value7.setText("7");
        btn_value7.setBorder(null);
        btn_value7.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btn_value7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_value7ActionPerformed(evt);
            }
        });

        btn_value8.setBackground(new java.awt.Color(0, 0, 0));
        btn_value8.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 18)); // NOI18N
        btn_value8.setForeground(new java.awt.Color(255, 255, 255));
        btn_value8.setText("8");
        btn_value8.setBorder(null);
        btn_value8.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btn_value8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_value8ActionPerformed(evt);
            }
        });

        btn_Sum.setBackground(new java.awt.Color(0, 0, 0));
        btn_Sum.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 18)); // NOI18N
        btn_Sum.setForeground(new java.awt.Color(255, 255, 255));
        btn_Sum.setText("+");
        btn_Sum.setBorder(null);
        btn_Sum.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btn_Sum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_SumActionPerformed(evt);
            }
        });

        btn_value9.setBackground(new java.awt.Color(0, 0, 0));
        btn_value9.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 18)); // NOI18N
        btn_value9.setForeground(new java.awt.Color(255, 255, 255));
        btn_value9.setText("9");
        btn_value9.setBorder(null);
        btn_value9.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btn_value9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_value9ActionPerformed(evt);
            }
        });

        btn_ClearResult.setBackground(new java.awt.Color(0, 0, 0));
        btn_ClearResult.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 18)); // NOI18N
        btn_ClearResult.setForeground(new java.awt.Color(255, 255, 255));
        btn_ClearResult.setText("CE");
        btn_ClearResult.setBorder(null);
        btn_ClearResult.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btn_ClearResult.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ClearResultActionPerformed(evt);
            }
        });

        btn_value4.setBackground(new java.awt.Color(0, 0, 0));
        btn_value4.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 18)); // NOI18N
        btn_value4.setForeground(new java.awt.Color(255, 255, 255));
        btn_value4.setText("4");
        btn_value4.setBorder(null);
        btn_value4.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btn_value4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_value4ActionPerformed(evt);
            }
        });

        btn_value5.setBackground(new java.awt.Color(0, 0, 0));
        btn_value5.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 18)); // NOI18N
        btn_value5.setForeground(new java.awt.Color(255, 255, 255));
        btn_value5.setText("5");
        btn_value5.setBorder(null);
        btn_value5.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btn_value5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_value5ActionPerformed(evt);
            }
        });

        btn_value6.setBackground(new java.awt.Color(0, 0, 0));
        btn_value6.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 18)); // NOI18N
        btn_value6.setForeground(new java.awt.Color(255, 255, 255));
        btn_value6.setText("6");
        btn_value6.setBorder(null);
        btn_value6.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btn_value6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_value6ActionPerformed(evt);
            }
        });

        btn_ClearVariebleResult.setBackground(new java.awt.Color(0, 0, 0));
        btn_ClearVariebleResult.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 18)); // NOI18N
        btn_ClearVariebleResult.setForeground(new java.awt.Color(255, 255, 255));
        btn_ClearVariebleResult.setText("C");
        btn_ClearVariebleResult.setBorder(null);
        btn_ClearVariebleResult.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btn_ClearVariebleResult.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ClearVariebleResultActionPerformed(evt);
            }
        });

        btn_Subtraction.setBackground(new java.awt.Color(0, 0, 0));
        btn_Subtraction.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 18)); // NOI18N
        btn_Subtraction.setForeground(new java.awt.Color(255, 255, 255));
        btn_Subtraction.setText("-");
        btn_Subtraction.setBorder(null);
        btn_Subtraction.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btn_Subtraction.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_SubtractionActionPerformed(evt);
            }
        });

        btn_value1.setBackground(new java.awt.Color(0, 0, 0));
        btn_value1.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 18)); // NOI18N
        btn_value1.setForeground(new java.awt.Color(255, 255, 255));
        btn_value1.setText("1");
        btn_value1.setBorder(null);
        btn_value1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btn_value1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_value1ActionPerformed(evt);
            }
        });

        btn_value2.setBackground(new java.awt.Color(0, 0, 0));
        btn_value2.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 18)); // NOI18N
        btn_value2.setForeground(new java.awt.Color(255, 255, 255));
        btn_value2.setText("2");
        btn_value2.setBorder(null);
        btn_value2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btn_value2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_value2ActionPerformed(evt);
            }
        });

        btn_value3.setBackground(new java.awt.Color(0, 0, 0));
        btn_value3.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 18)); // NOI18N
        btn_value3.setForeground(new java.awt.Color(255, 255, 255));
        btn_value3.setText("3");
        btn_value3.setBorder(null);
        btn_value3.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btn_value3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_value3ActionPerformed(evt);
            }
        });

        btn_Equal.setBackground(new java.awt.Color(0, 0, 0));
        btn_Equal.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 18)); // NOI18N
        btn_Equal.setForeground(new java.awt.Color(255, 255, 255));
        btn_Equal.setText("=");
        btn_Equal.setBorder(null);
        btn_Equal.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btn_Equal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_EqualActionPerformed(evt);
            }
        });

        btn_Multiplication.setBackground(new java.awt.Color(0, 0, 0));
        btn_Multiplication.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 18)); // NOI18N
        btn_Multiplication.setForeground(new java.awt.Color(255, 255, 255));
        btn_Multiplication.setText("*");
        btn_Multiplication.setBorder(null);
        btn_Multiplication.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btn_Multiplication.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_MultiplicationActionPerformed(evt);
            }
        });

        btn_value0.setBackground(new java.awt.Color(0, 0, 0));
        btn_value0.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 18)); // NOI18N
        btn_value0.setForeground(new java.awt.Color(255, 255, 255));
        btn_value0.setText("0");
        btn_value0.setBorder(null);
        btn_value0.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btn_value0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_value0ActionPerformed(evt);
            }
        });

        btn_Score.setBackground(new java.awt.Color(0, 0, 0));
        btn_Score.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 18)); // NOI18N
        btn_Score.setForeground(new java.awt.Color(255, 255, 255));
        btn_Score.setText(".");
        btn_Score.setBorder(null);
        btn_Score.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btn_Score.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ScoreActionPerformed(evt);
            }
        });

        btn_Division.setBackground(new java.awt.Color(0, 0, 0));
        btn_Division.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 18)); // NOI18N
        btn_Division.setForeground(new java.awt.Color(255, 255, 255));
        btn_Division.setText("/");
        btn_Division.setBorder(null);
        btn_Division.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btn_Division.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_DivisionActionPerformed(evt);
            }
        });

        txt_Result.setBackground(new java.awt.Color(51, 51, 51));
        txt_Result.setFont(new java.awt.Font("Microsoft JhengHei UI", 1, 24)); // NOI18N
        txt_Result.setForeground(new java.awt.Color(255, 255, 255));
        txt_Result.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txt_Result.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(51, 51, 51), new java.awt.Color(51, 51, 51)));

        btn_Square.setBackground(new java.awt.Color(0, 0, 0));
        btn_Square.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 18)); // NOI18N
        btn_Square.setForeground(new java.awt.Color(255, 255, 255));
        btn_Square.setText("x²");
        btn_Square.setBorder(null);
        btn_Square.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btn_Square.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_SquareActionPerformed(evt);
            }
        });

        btn_Cube.setBackground(new java.awt.Color(0, 0, 0));
        btn_Cube.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 18)); // NOI18N
        btn_Cube.setForeground(new java.awt.Color(255, 255, 255));
        btn_Cube.setText("x³");
        btn_Cube.setBorder(null);
        btn_Cube.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btn_Cube.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_CubeActionPerformed(evt);
            }
        });

        btn_SquareRoot.setBackground(new java.awt.Color(0, 0, 0));
        btn_SquareRoot.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 18)); // NOI18N
        btn_SquareRoot.setForeground(new java.awt.Color(255, 255, 255));
        btn_SquareRoot.setText("√");
        btn_SquareRoot.setBorder(null);
        btn_SquareRoot.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btn_SquareRoot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_SquareRootActionPerformed(evt);
            }
        });

        btn_Factorial.setBackground(new java.awt.Color(0, 0, 0));
        btn_Factorial.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 18)); // NOI18N
        btn_Factorial.setForeground(new java.awt.Color(255, 255, 255));
        btn_Factorial.setText("n!");
        btn_Factorial.setBorder(null);
        btn_Factorial.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btn_Factorial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_FactorialActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txt_Result)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btn_value7, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn_value8, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn_value9, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn_ClearResult, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn_Sum, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btn_value4, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn_value5, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn_value6, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn_ClearVariebleResult, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn_Subtraction, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(btn_value1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btn_value2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(btn_value0, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btn_value3, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btn_Score, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn_Equal, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btn_Multiplication, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btn_Division, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btn_Square, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_Cube, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_SquareRoot, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_Factorial, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(15, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(txt_Result, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btn_value7, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_value8, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_value9, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_Sum, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_ClearResult, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btn_value4, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_value5, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_value6, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_Subtraction, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_ClearVariebleResult, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btn_Multiplication, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btn_Division, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(btn_value1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btn_value2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btn_value3, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(btn_value0, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btn_Score, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(btn_Equal, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btn_Square, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_Cube, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_SquareRoot, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_Factorial, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        jPanel2.setBackground(new java.awt.Color(0, 0, 0));
        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0)));

        lbl_Calculator.setBackground(new java.awt.Color(255, 255, 255));
        lbl_Calculator.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 24)); // NOI18N
        lbl_Calculator.setForeground(new java.awt.Color(153, 153, 153));
        lbl_Calculator.setText("CALCULADORA");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(88, 88, 88)
                .addComponent(lbl_Calculator, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(88, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(lbl_Calculator)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_value9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_value9ActionPerformed
        txt_Result.setText(txt_Result.getText()+9);
    }//GEN-LAST:event_btn_value9ActionPerformed

    private void btn_value6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_value6ActionPerformed
        txt_Result.setText(txt_Result.getText()+6);
    }//GEN-LAST:event_btn_value6ActionPerformed

    private void btn_value3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_value3ActionPerformed
        txt_Result.setText(txt_Result.getText()+3);
    }//GEN-LAST:event_btn_value3ActionPerformed

    private void btn_ScoreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ScoreActionPerformed
        txt_Result.setText(txt_Result.getText()+".");
    }//GEN-LAST:event_btn_ScoreActionPerformed

    private void btn_value0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_value0ActionPerformed
        txt_Result.setText(txt_Result.getText()+0);
    }//GEN-LAST:event_btn_value0ActionPerformed

    private void btn_value1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_value1ActionPerformed
        txt_Result.setText(txt_Result.getText()+1);
    }//GEN-LAST:event_btn_value1ActionPerformed

    private void btn_value2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_value2ActionPerformed
        txt_Result.setText(txt_Result.getText()+2);
    }//GEN-LAST:event_btn_value2ActionPerformed

    private void btn_value4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_value4ActionPerformed
        txt_Result.setText(txt_Result.getText()+4);
    }//GEN-LAST:event_btn_value4ActionPerformed

    private void btn_value5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_value5ActionPerformed
        txt_Result.setText(txt_Result.getText()+5);
    }//GEN-LAST:event_btn_value5ActionPerformed

    private void btn_value7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_value7ActionPerformed
        txt_Result.setText(txt_Result.getText()+7);
    }//GEN-LAST:event_btn_value7ActionPerformed

    private void btn_value8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_value8ActionPerformed
        txt_Result.setText(txt_Result.getText()+8);
    }//GEN-LAST:event_btn_value8ActionPerformed

    private void btn_ClearResultActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ClearResultActionPerformed
        txt_Result.setText("");
    }//GEN-LAST:event_btn_ClearResultActionPerformed

    private void btn_SumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_SumActionPerformed

        value1= Double.parseDouble(txt_Result.getText());
        txt_Result.setText("");
        signal="sum";
    }//GEN-LAST:event_btn_SumActionPerformed

    private void btn_EqualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_EqualActionPerformed
        value2 =Double.parseDouble(txt_Result.getText());
        if (signal == "sum"){
            txt_Result.setText(String.valueOf(value1 + value2));
        }if (signal == "subtraction"){
            txt_Result.setText(String.valueOf(value1 - value2));
        }if (signal == "multiplication"){
            txt_Result.setText(String.valueOf(value1 * value2));
        }if (signal == "division"){
            txt_Result.setText(String.valueOf(value1 / value2));
        }
    }//GEN-LAST:event_btn_EqualActionPerformed

    private void btn_SubtractionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_SubtractionActionPerformed
        value1= Double.parseDouble(txt_Result.getText());
        txt_Result.setText("");
        signal="subtraction";
    }//GEN-LAST:event_btn_SubtractionActionPerformed

    private void btn_MultiplicationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_MultiplicationActionPerformed
        value1= Double.parseDouble(txt_Result.getText());
        txt_Result.setText("");
        signal="multiplication";
    }//GEN-LAST:event_btn_MultiplicationActionPerformed

    private void btn_DivisionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_DivisionActionPerformed
        value1= Double.parseDouble(txt_Result.getText());
        txt_Result.setText("");
        signal="division";
    }//GEN-LAST:event_btn_DivisionActionPerformed

    private void btn_ClearVariebleResultActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ClearVariebleResultActionPerformed
        value1 = null;
        value2 = null;
        txt_Result.setText("");
    }//GEN-LAST:event_btn_ClearVariebleResultActionPerformed

    private void btn_SquareActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_SquareActionPerformed
        value1= Double.parseDouble(txt_Result.getText());
        txt_Result.setText(String.valueOf(Math.pow(value1, 2)));
    }//GEN-LAST:event_btn_SquareActionPerformed

    private void btn_CubeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_CubeActionPerformed
        value1= Double.parseDouble(txt_Result.getText());
        txt_Result.setText(String.valueOf(Math.pow(value1, 3)));
    }//GEN-LAST:event_btn_CubeActionPerformed

    private void btn_SquareRootActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_SquareRootActionPerformed
        value1= Double.parseDouble(txt_Result.getText());
        txt_Result.setText(String.valueOf(Math.sqrt(value1)));
    }//GEN-LAST:event_btn_SquareRootActionPerformed

    private void btn_FactorialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_FactorialActionPerformed
        value1= Double.parseDouble(txt_Result.getText());
        n = value1-1;
        factorial = value1;
        while (n >1){
            factorial = factorial*n;
            n --;
        }
        txt_Result.setText(String.valueOf(factorial));
    }//GEN-LAST:event_btn_FactorialActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormCalculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormCalculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormCalculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormCalculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormCalculadora().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_ClearResult;
    private javax.swing.JButton btn_ClearVariebleResult;
    private javax.swing.JButton btn_Cube;
    private javax.swing.JButton btn_Division;
    private javax.swing.JButton btn_Equal;
    private javax.swing.JButton btn_Factorial;
    private javax.swing.JButton btn_Multiplication;
    private javax.swing.JButton btn_Score;
    private javax.swing.JButton btn_Square;
    private javax.swing.JButton btn_SquareRoot;
    private javax.swing.JButton btn_Subtraction;
    private javax.swing.JButton btn_Sum;
    private javax.swing.JButton btn_value0;
    private javax.swing.JButton btn_value1;
    private javax.swing.JButton btn_value2;
    private javax.swing.JButton btn_value3;
    private javax.swing.JButton btn_value4;
    private javax.swing.JButton btn_value5;
    private javax.swing.JButton btn_value6;
    private javax.swing.JButton btn_value7;
    private javax.swing.JButton btn_value8;
    private javax.swing.JButton btn_value9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lbl_Calculator;
    private javax.swing.JTextField txt_Result;
    // End of variables declaration//GEN-END:variables
}
